version: '3'

tasks:
  format:
    desc: Run clang-format over all project files
    cmds:
      - clang-format -i -style=file src/erin_next*.cpp include/erin_next/*.h
  init:
    desc: Initialize the build directory
    cmds:
      - mkdir build
      - cmake -S . -B build -DERIN_TESTING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=1
  rebuild:
    desc: Rebuild the application
    cmds:
      - cmake --build build --config Release
