version: '3'

tasks:
  format:
    desc: Run clang-format over all project files
    cmds:
      - clang-format -i -style=file src/erin_next*.cpp include/erin_next/*.h
  init:
    desc: Initialize the build directory
    cmds:
      - mkdir build
      - cmake -S . -B build -DERIN_TESTING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=1
  build:
    desc: (Re)build the application
    cmds:
      - cmake --build build --config Release -j 4
  test:
    desc: Run the test suite
    dir: 'docs/erin_next_examples'
    cmds:
      - python regress.py
  dbg-init:
    desc: Make a debug build
    cmds:
      - mkdir build-db
      - cmake -S . -B build-db -DERIN_TESTING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=1
  dbg-build:
    desc: Build in debug mode
    cmds:
      - cmake --build build-db --config Debug -j 4
  exercise:
    desc: Runs the current exercise
    dir: 'docs/erin_next_examples'
    cmds:
      - ../../build/bin/erin_next_cli ex29.toml
