version: '3'

tasks:
  format:
    desc: Run clang-format over all project files
    cmds:
      - clang-format -i -style=file src/*.cpp
      - clang-format -i -style=file include/**/*.h
      #- clang-format -i -style=file test/*.cpp
      - clang-format -i -style=file apps/*.cpp
  checkfmt:
    desc: Check if there are any formatting problems
    cmds:
      - clang-format --dry-run --Werror src/*.cpp
      - clang-format --dry-run --Werror include/**/*.h
      #- clang-format --dry-run --Werror test/*.cpp
      - clang-format --dry-run --Werror apps/**/*.h
  init:
    desc: Initialize the build directory
    cmds:
      - mkdir build
      - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DERIN_TESTING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=1
  build:
    desc: (Re)build the application
    cmds:
      - cmake --build build --config Release -j 4
  test:
    desc: Run the test suite
    dir: 'docs/erin_next_examples'
    cmds:
      - python regress.py
  ex:
    desc: Run the given exercise. Pass '-- ex29.toml' to run example 29
    dir: 'docs/erin_next_examples'
    cmds:
      - ../../build/bin/erin_next_cli {{.CLI_ARGS}}
  db-init:
    desc: Make a debug build
    cmds:
      - mkdir build-db
      - cmake -S . -B build-db -DCMAKE_BUILD_TYPE=Debug -DERIN_TESTING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=1
  db-build:
    desc: Build in debug mode
    cmds:
      - cmake --build build-db --config Debug -j 4
  db:
    desc: Runs the current exercise
    dir: 'docs/erin_next_examples'
    cmds:
      - lldb ../../build-db/bin/erin_next_cli -- ex29.toml
