[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "hours"
max_time = 4
[streams.electricity]
type = "electricity_medium_voltage"
[streams.diesel]
type = "diesel_fuel"
[streams.diesel.other_rate_units]
gallons__hour = 0.026520422449113276
liters__hour = 0.1003904071388734
[streams.diesel.other_quantity_units]
gallons = 7.366784013642577e-6
liters = 2.7886224205242612e-5
############################################################
[loads.building_electrical]
time_unit = "hours"
rate_unit = "kW"
time_rate_pairs = [[0.0,1.0],[4.0]]
############################################################
[components.electric_utility]
type = "source"
# Point of Common Coupling for Electric Utility
output_stream = "electricity"
[components.cluster_01_electric]
type = "load"
input_stream = "electricity"
loads_by_scenario.blue_sky = "building_electrical"
############################################################
[networks.normal_operations]
# Specify network as an array of 2, 4, or 6-tuples. The interpretation is as
# follows:
# 2-tuples: [<source_component_id>, <sink_component_id>]
# this maps to:
# [ <component_1_id=source_component_id>, <component_1_port_type="outflow">, <component_1_port_number=0>,
#   <component_2_id=  sink_component_id>, <component_2_port_type= "inflow">, <component_2_port_number=0>]
# 4-tuple: [<c1_id>, <c1_port_type>, <c2_id>, <c2_port_type>]
# this maps to:
# [ <component_1_id=c1_id>, <component_1_port_type=c1_port_type>, <component_1_port_number=0>,
#   <component_2_id=c2_id>, <component_2_port_type=c2_port_type>, <component_2_port_number=0>]
# 6-tuple: [ <component_1_id>, <component_1_port_type>, <component_1_port_number>,
#            <component_2_id>, <component_2_port_type>, <component_2_port_number>]       
connections = [["electric_utility", "cluster_01_electric"]]
############################################################
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = {type = "fixed", value = 0}
duration = 4
max_occurrences = 1
network = "normal_operations"
