[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "hours"
max_time = 4
############################################################
[loads.building_electrical]
csv_file = "ex02.csv"
############################################################
[components.electric_utility]
type = "source"
# Point of Common Coupling for Electric Utility
outflow = "electricity"
[components.cluster_01_electric]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "building_electrical"
############################################################
[networks.normal_operations]
connections = [["electric_utility:OUT(0)", "cluster_01_electric:IN(0)", "electricity"]]
############################################################
[cdf.immediately]
type = "fixed"
value = 0
time_unit = "hours"
############################################################
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = "immediately"
duration = 4
max_occurrences = 1
network = "normal_operations"
