[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "hours"
max_time = 4
[streams.electricity]
type = "electricity_medium_voltage"
############################################################
[loads.building_electrical]
csv_file = "ex02.csv"
############################################################
[components.electric_utility]
type = "source"
# Point of Common Coupling for Electric Utility
output_stream = "electricity"
[components.cluster_01_electric]
type = "load"
input_stream = "electricity"
loads_by_scenario.blue_sky = "building_electrical"
############################################################
[networks.normal_operations]
# REFAC connections = [["electric_utility:OUT(0)", "cluster_01_electric:IN(0)", "electricity_medium_voltage"]]
connections = [["electric_utility", "cluster_01_electric"]]
############################################################
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = {type = "fixed", value = 0}
duration = 4
max_occurrences = 1
network = "normal_operations"
