[stream_info]
# The commonality across all streams.
# We need to know what the common rate unit and quantity unit is.
# The rate unit should be the quantity unit per unit of time.
rate_unit = "kW"
quantity_unit = "kJ"
# seconds_per_time_unit : Number
# defines how many seconds per unit of time used to specify the quantity unit
# here since we are using kW and kJ, the answer is 1.0 second.
# However, if we were doing kW and kWh, we would use 3600 s (i.e., 1 hour) here.
seconds_per_time_unit = 1.0 
[streams.electricity]
type = "electricity_medium_voltage"
############################################################
[loads.building_electrical]
csv_file = "ex02.csv"
############################################################
[components.electric_utility]
type = "source"
# Point of Common Coupling for Electric Utility
output_stream = "electricity"
[components.cluster_01_electric]
type = "load"
input_stream = "electricity"
[components.cluster_01_electric.load_profiles_by_scenario]
blue_sky = "building_electrical"
############################################################
[networks.normal_operations]
connections = [["electric_utility", "cluster_01_electric"]]
############################################################
[scenarios.blue_sky]
time_units = "hours"
occurrence_distribution = {type = "fixed", value = 0}
duration = 4
max_occurrences = 1
network = "normal_operations"
