[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "years"
max_time = 100
fixed_random_series = [0.9,0.1,0.1,0.1,0.1,0.9,0.9,0.9]
[loads.building_electrical]
csv_file = "ex03.csv"
[components.electric_utility]
type = "source"
outflow = "electricity"
fragilities = ["highly_vulnerable_to_wind"]
max_outflow = 10.0
[components.cluster_01_electric]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "building_electrical"
loads_by_scenario.class_1_hurricane = "building_electrical"
loads_by_scenario.class_4_hurricane = "building_electrical"
loads_by_scenario.class_5_hurricane = "building_electrical"
[components.emergency_generator]
type = "source"
outflow = "electricity"
fragilities = ["somewhat_vulnerable_to_flooding"]
[components.bus]
type = "muxer"
flow = "electricity"
num_inflows = 2
num_outflows = 1
dispatch_strategy = "in_order"
fragilities = ["highly_vulnerable_to_wind", "somewhat_vulnerable_to_flooding"]
[fragility.somewhat_vulnerable_to_flooding]
vulnerable_to = "inundation_depth_ft"
type = "linear"
lower_bound = 6.0
upper_bound = 14.0
[fragility.highly_vulnerable_to_wind]
vulnerable_to = "wind_speed_mph"
type = "linear"
lower_bound = 80.0
upper_bound = 180.0
[networks.normal_operations]
connections = [["electric_utility:OUT(0)", "cluster_01_electric:IN(0)", "electricity"]]
[networks.emergency_operations]
connections = [
  ["electric_utility:OUT(0)", "bus:IN(0)", "electricity"],
  ["emergency_generator:OUT(0)", "bus:IN(1)", "electricity"],
  ["bus:OUT(0)", "cluster_01_electric:IN(0)", "electricity"]]
[cdf.immediately]
type = "fixed"
value = 0
time_unit = "hours"
[cdf.every_10_years]
type = "fixed"
value = 10
time_unit = "years"
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = "immediately"
duration = 8760
max_occurrences = 1
network = "normal_operations"
[scenarios.class_4_hurricane]
time_unit = "hours"
occurrence_distribution = "every_10_years"
duration = 336
max_occurrences = -1
network = "emergency_operations"
intensity.wind_speed_mph = 156
intensity.inundation_depth_ft = 8
