[simulation_info]
input_format_version = "0.2"
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "years"
max_time = 100
fixed_random_series = [0.9,0.1,0.1,0.1,0.1,0.9,0.9,0.9]
[loads.building_electrical]
#csv_file = "ex03.csv"
time_unit = "hours"
rate_unit = "kW"
time_rate_pairs = [
  [0.0, 1.0],
  [1200.0, 10.0],
  [2400.0, 1.0],
  [3600.0, 0.0],
]
[components.electric_utility]
type = "source"
outflow = "electricity"
fragility_modes = ["highly_vulnerable_to_wind"]
rate_unit = "kW"
max_outflow = 10.0
[components.cluster_01_electric]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "building_electrical"
loads_by_scenario.class_4_hurricane = "building_electrical"
[components.emergency_generator]
type = "source"
outflow = "electricity"
fragility_modes = ["somewhat_vulnerable_to_flooding"]
[components.bus]
type = "muxer"
flow = "electricity"
num_inflows = 2
num_outflows = 1
fragility_modes = ["highly_vulnerable_to_wind", "somewhat_vulnerable_to_flooding"]
[fragility_mode.somewhat_vulnerable_to_flooding]
fragility_curve = "somewhat_vulnerable_to_flooding_curve"
[fragility_mode.highly_vulnerable_to_wind]
fragility_curve = "highly_vulnerable_to_wind_curve"
[fragility_curve.somewhat_vulnerable_to_flooding_curve]
vulnerable_to = "inundation_depth_ft"
type = "linear"
lower_bound = 6.0
upper_bound = 14.0
[fragility_curve.highly_vulnerable_to_wind_curve]
vulnerable_to = "wind_speed_mph"
type = "linear"
lower_bound = 80.0
upper_bound = 180.0
[network]
connections = [
  ["electric_utility:OUT(0)", "bus:IN(0)", "electricity"],
  ["emergency_generator:OUT(0)", "bus:IN(1)", "electricity"],
  ["bus:OUT(0)", "cluster_01_electric:IN(0)", "electricity"]]
[dist.immediately]
type = "fixed"
value = 0
time_unit = "hours"
[dist.every_10_years]
type = "fixed"
value = 10
time_unit = "years"
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = "immediately"
duration = 8760
max_occurrences = 1
[scenarios.class_4_hurricane]
time_unit = "hours"
occurrence_distribution = "every_10_years"
duration = 336
max_occurrences = -1
intensity.wind_speed_mph = 156
intensity.inundation_depth_ft = 8
