[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "seconds"
max_time = 10
[loads.electric_load]
time_unit = "seconds"
rate_unit = "kW"
time_rate_pairs = [[0.0,10.0],[10.0,0.0]]
[loads.heating_load]
time_unit = "seconds"
rate_unit = "kW"
time_rate_pairs = [[0.0,1.0],[10.0,0.0]]
[components.S]
# S = source of natural 
type = "source"
outflow = "natural_gas"
[components.LE]
# LE = load, electrical
type = "load"
inflow = "electricity"
loads_by_scenario.scenario01 = "electric_load"
[components.LT]
# LT = load, thermal
type = "load"
inflow = "district_hot_water"
loads_by_scenario.scenario01 = "heating_load"
[components.C0]
# C0 = converter 0, natural-gas to electricity
type = "converter"
inflow = "natural_gas"
outflow = "electricity"
lossflow = "waste_heat"
constant_efficiency = 0.5
[components.C1]
# C1 = converter 1, waste-heat to district hot water (heat exchanger)
type = "converter"
inflow = "waste_heat"
outflow = "district_hot_water"
lossflow = "waste_heat"
constant_efficiency = 0.5
[network]
connections = [["S:OUT(0)", "C0:IN(0)", "natural_gas"],
               ["C0:OUT(0)", "LE:IN(0)", "electricity"],
               ["C0:OUT(1)", "C1:IN(0)", "waste_heat"],
               ["C1:OUT(0)", "LT:IN(0)", "district_hot_water"]]
[dist.immediately]
type = "fixed"
value = 0
time_unit = "hours"
[scenarios.scenario01]
time_unit = "seconds"
occurrence_distribution = "immediately"
duration = 10
max_occurrences = 1
