# Based on GEF template for 2.3.1.2. University of British Columbia
[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "years"
max_time = 100
fixed_random = 0.5
[loads.normal_electric_mission_critical_consumer]
csv_file = "ex07-normal-electric-mcc.csv"
[loads.normal_electric_other_consumer]
csv_file = "ex07-normal-electric-oc.csv"
[loads.normal_steam_mission_critical_consumer]
csv_file = "ex07-normal-steam-mcc.csv"
[loads.normal_steam_other_consumer]
csv_file = "ex07-normal-steam-oc.csv"
[loads.normal_heating_mission_critical_consumer]
csv_file = "ex07-normal-heating-mcc.csv"
[loads.normal_heating_other_consumer]
csv_file = "ex07-normal-heating-oc.csv"
[loads.emergency_electric_mission_critical_consumer]
csv_file = "ex07-emergency-electric-mcc.csv"
[loads.emergency_electric_other_consumer]
csv_file = "ex07-emergency-electric-oc.csv"
[loads.emergency_steam_mission_critical_consumer]
csv_file = "ex07-emergency-steam-mcc.csv"
[loads.emergency_steam_other_consumer]
csv_file = "ex07-emergency-steam-oc.csv"
[loads.emergency_heating_mission_critical_consumer]
csv_file = "ex07-emergency-heating-mcc.csv"
[loads.emergency_heating_other_consumer]
csv_file = "ex07-emergency-heating-oc.csv"
[fragility.somewhat_vulnerable_to_flooding]
vulnerable_to = "inundation_depth_ft"
type = "linear"
lower_bound = 6.0
upper_bound = 14.0
[fragility.highly_vulnerable_to_flooding]
vulnerable_to = "inundation_depth_ft"
type = "linear"
lower_bound = 2.0
upper_bound = 6.0
[fragility.highly_vulnerable_to_wind]
vulnerable_to = "wind_speed_mph"
type = "linear"
lower_bound = 80.0
upper_bound = 180.0
[components.electric_utility]
type = "source"
outflow = "electricity"
fragilities = ["highly_vulnerable_to_wind", "highly_vulnerable_to_flooding"]
[components.natural_gas_utility]
type = "source"
outflow = "natural_gas"
fragilities = ["somewhat_vulnerable_to_flooding"]
[components.biomethane_source]
type = "source"
outflow = "natural_gas"
fragilities = ["somewhat_vulnerable_to_flooding"]
[components.biomass_source]
type = "source"
outflow = "biomass"
fragilities = ["highly_vulnerable_to_flooding"]
[components.chp_inputs]
type = "muxer"
flow = "natural_gas"
num_inflows = 2
num_outflows = 1
dispatch_strategy = "in_order"
fragilities = ["somewhat_vulnerable_to_flooding"]
[components.chp_electricity]
type = "converter"
inflow = "natural_gas"
outflow = "electricity"
lossflow = "waste_heat"
constant_efficiency = 0.35
[components.chp_steam]
type = "converter"
inflow = "waste_heat"
outflow = "steam"
lossflow = "waste_heat"
constant_efficiency = 0.35
[components.chp_heating]
type = "converter"
inflow = "waste_heat"
outflow = "heating"
lossflow = "waste_heat"
constant_efficiency = 0.30
[components.natural_gas_boiler_heating]
type = "converter"
inflow = "natural_gas"
outflow = "heating"
lossflow = "waste_heat"
constant_efficiency = 0.45
fragilities = ["somewhat_vulnerable_to_flooding"]
[components.biomass_boiler_steam]
type = "converter"
inflow = "biomass"
outflow = "steam"
lossflow = "waste_heat"
constant_efficiency = 0.45
fragilities = ["somewhat_vulnerable_to_flooding"]
[components.biomass_boiler_heating]
type = "converter"
inflow = "waste_heat"
outflow = "heating"
lossflow = "waste_heat"
constant_efficiency = 0.3
[components.mission_critical_consumer_steam]
type = "load"
inflow = "steam"
loads_by_scenario.blue_sky = "normal_steam_mission_critical_consumer"
loads_by_scenario.category_4_hurricane = "emergency_steam_mission_critical_consumer"
[components.other_consumer_steam]
type = "load"
inflow = "steam"
loads_by_scenario.blue_sky = "normal_steam_other_consumer"
loads_by_scenario.category_4_hurricane = "emergency_steam_other_consumer"
[components.mission_critical_consumer_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "normal_electric_mission_critical_consumer"
loads_by_scenario.category_4_hurricane = "emergency_electric_mission_critical_consumer"
[components.other_consumer_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "normal_electric_other_consumer"
loads_by_scenario.category_4_hurricane = "emergency_electric_other_consumer"
[components.mission_critical_consumer_heating]
type = "load"
inflow = "heating"
loads_by_scenario.blue_sky = "normal_heating_mission_critical_consumer"
loads_by_scenario.category_4_hurricane = "emergency_heating_mission_critical_consumer"
[components.other_consumer_heating]
type = "load"
inflow = "heating"
loads_by_scenario.blue_sky = "normal_heating_other_consumer"
loads_by_scenario.category_4_hurricane = "emergency_heating_other_consumer"
[components.natural_gas_manifold]
type = "muxer"
flow = "natural_gas"
num_inflows = 1
num_outflows = 2
dispatch_strategy = "in_order"
[components.electric_bus]
type = "muxer"
flow = "electricity"
num_inflows = 2
num_outflows = 2
dispatch_strategy = "in_order"
[components.steam_manifold]
type = "muxer"
flow = "steam"
num_inflows = 2
num_outflows = 2
dispatch_strategy = "in_order"
[components.heating_manifold]
type = "muxer"
flow = "heating"
num_inflows = 3
num_outflows = 2
dispatch_strategy = "in_order"
[networks.nw_1]
connections = [
  # Natural Gas and Biomethane Network
  ["natural_gas_utility:OUT(0)", "natural_gas_manifold:IN(0)", "natural_gas"],
  ["biomethane_source:OUT(0)", "chp_inputs:IN(0)", "natural_gas"],
  ["natural_gas_manifold:OUT(0)", "chp_inputs:IN(1)", "natural_gas"],
  ["chp_inputs:OUT(0)", "chp_electricity:IN(0)", "natural_gas"],
  ["natural_gas_manifold:OUT(1)", "natural_gas_boiler_heating:IN(0)", "natural_gas"],
  # Biomass Network
  ["biomass_source:OUT(0)", "biomass_boiler_steam:IN(0)", "biomass"],
  # Electric Network
  ["electric_utility:OUT(0)", "electric_bus:IN(1)", "electricity"],
  ["chp_electricity:OUT(0)", "electric_bus:IN(0)", "electricity"],
  ["electric_bus:OUT(0)", "mission_critical_consumer_electricity:IN(0)", "electricity"],
  ["electric_bus:OUT(1)", "other_consumer_electricity:IN(0)", "electricity"],
  # Steam Network
  ["chp_steam:OUT(0)", "steam_manifold:IN(0)", "steam"],
  ["biomass_boiler_steam:OUT(0)", "steam_manifold:IN(1)", "steam"],
  ["steam_manifold:OUT(0)", "mission_critical_consumer_steam:IN(0)", "steam"],
  ["steam_manifold:OUT(1)", "other_consumer_steam:IN(0)", "steam"],
  # Heating Network
  ["chp_heating:OUT(0)", "heating_manifold:IN(0)", "heating"],
  ["biomass_boiler_heating:OUT(0)", "heating_manifold:IN(1)", "heating"],
  ["natural_gas_boiler_heating:OUT(0)", "heating_manifold:IN(2)", "heating"],
  ["heating_manifold:OUT(0)", "mission_critical_consumer_heating:IN(0)", "heating"],
  ["heating_manifold:OUT(1)", "other_consumer_heating:IN(0)", "heating"],
  # Waste Heat Network
  ["chp_electricity:OUT(1)", "chp_steam:IN(0)", "waste_heat"],
  ["chp_steam:OUT(1)", "chp_heating:IN(0)", "waste_heat"],
  ["biomass_boiler_steam:OUT(1)", "biomass_boiler_heating:IN(0)", "waste_heat"]]
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = {type = "fixed", value = 0}
duration = 8760
max_occurrences = 1
network = "nw_1"
[scenarios.category_4_hurricane]
time_unit = "hours"
occurrence_distribution = {type = "fixed", time_unit="years", value = 30}
duration = 336
max_occurrences = -1
network = "nw_1"
intensity.wind_speed_mph = 156
intensity.inundation_depth_ft = 8
