[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "seconds"
max_time = 10
############################################################
[loads.profile1]
time_unit = "seconds"
rate_unit = "kW"
time_rate_pairs = [[0.0,100.0],[10.0,0.0]]
############################################################
[cdf.cdf_break]
type = "fixed"
value = 5
time_unit = "seconds"
[cdf.cdf_repair]
type = "fixed"
value = 2
time_unit = "seconds"
[cdf.immediately]
type = "fixed"
value = 0
time_unit = "hours"
############################################################
[failure_mode.fm]
failure_cdf = "cdf_break"
repair_cdf = "cdf_repair"
############################################################
[components.S1]
type = "source"
outflow = "electricity"
failure_modes = ["fm"]
[components.L1]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "profile1"
############################################################
[networks.normal_operations]
connections = [
  ["S1:OUT(0)", "L1:IN(0)", "electricity"]
  ]
############################################################
[scenarios.blue_sky]
time_unit = "seconds"
occurrence_distribution = "immediately"
duration = 10
max_occurrences = 1
network = "normal_operations"
calculate_reliability = true
