[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "seconds"
max_time = 10
[loads.environment]
time_unit = "seconds"
rate_unit = "kW"
time_rate_pairs = [[0.0,1000.0],[10.0,0.0]]
[loads.cooling]
time_unit = "seconds"
rate_unit = "kW"
time_rate_pairs = [[0.0,50.0],[5.0,120.0],[8.0,100.0],[10.0,0.0]]
[components.utility_electricity]
type = "source"
outflow = "electricity"
[components.cooling_load]
type = "uncontrolled_source"
outflow = "heat_removed"
supply_by_scenario.blue_sky = "cooling"
[components.environment_sink]
type = "load"
inflow = "heat_removed"
loads_by_scenario.blue_sky = "environment"
[components.chiller]
type = "mover"
inflow0 = "heat_removed"
inflow1 = "electricity"
outflow = "heat_removed"
cop = 5.0
[networks.nw]
connections = [
    ["cooling_load:OUT(0)",  "chiller:IN(0)", "heat_removed"],
    ["utility_electricity:OUT(0)",  "chiller:IN(1)", "electricity"],
    ["chiller:OUT(0)", "environment_sink:IN(0)", "heat_removed"],
    ]
[cdf.immediately]
type = "fixed"
value = 0
time_unit = "hours"
[scenarios.blue_sky]
time_unit = "seconds"
occurrence_distribution = "immediately"
duration = 10
max_occurrences = 1
network = "nw"
