[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "hours"
max_time = 40
############################################################
[loads.building_electrical]
time_unit = "hours"
rate_unit = "kW"
time_rate_pairs = [[0.0,1.0],[40.0,0.0]]
############################################################
[components.S]
type = "source"
outflow = "electricity"
failure_modes = ["fm"]
[components.L]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "building_electrical"
############################################################
[dist.every_10]
type = "fixed"
value = 10
time_unit = "hours"
[dist.every_5]
type = "fixed"
value = 5
time_unit = "hours"
############################################################
[failure_mode.fm]
failure_cdf = "every_10"
repair_cdf = "every_5"
############################################################
[networks.nw]
connections = [["S:OUT(0)", "L:IN(0)", "electricity"]]
############################################################
[dist.immediately]
type = "fixed"
value = 0
time_unit = "hours"
############################################################
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = "immediately"
duration = 40
max_occurrences = 1
network = "nw"
calculate_reliability = true
