[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "hours"
max_time = 20
############## Loads ######################
[loads.normal_electric_bldg_a]
time_unit = "hours"
rate_unit = "kW"
time_rate_pairs = [[0.0,10.0],[20.0,0.0]]
[loads.normal_electric_bldg_b]
time_unit = "hours"
rate_unit = "kW"
time_rate_pairs = [[0.0,10.0],[20.0,0.0]]
[loads.normal_electric_bldg_c]
time_unit = "hours"
rate_unit = "kW"
time_rate_pairs = [[0.0,10.0],[20.0,0.0]]
############## Components #################
#### Sources ####
[components.utility_electrical]
type = "source"
outflow = "electricity"
max_outflow = 30.0
[components.diesel_resupply]
type = "source"
outflow = "fuel"
#### Buildings ####
[components.bldg_a_electric]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "normal_electric_bldg_a"
[components.bldg_b_electric]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "normal_electric_bldg_b"
[components.bldg_c_electric]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "normal_electric_bldg_c"
#### Electrical Components ###
[components.sub_sta_1]
type = "muxer"
stream = "electricity"
failure_modes = ["grid_outage"]
num_inflows = 1
num_outflows = 3
[components.xfer_a]
type = "muxer"
stream = "electricity"
num_inflows = 2  
num_outflows = 1
[components.gen_a]
type = "converter"
inflow = "fuel"
outflow = "electricity"
constant_efficiency = 0.2
[components.xfer_b]
type = "muxer"
stream = "electricity"
num_inflows = 2  
num_outflows = 1
[components.gen_b]
type = "converter"
inflow = "fuel"
outflow = "electricity"
constant_efficiency = 0.2
#### Fuel System Components ####
[components.fuel_truck]
type="muxer"
stream="fuel"
num_inflows = 1
num_outflows = 2
############## CDF ###########################
[cdf.every_10]
type = "fixed"
value = 10
time_unit = "hours"
[cdf.every_3]
type = "fixed"
value = 3
time_unit = "hours"
############# Failure Modes #####################
[failure_mode.grid_outage]
failure_cdf = "every_10"
repair_cdf = "every_3"
############## Networks #################
[networks.nw_electric]
connections = [
  # Electric Network
  ["utility_electrical:OUT(0)", "sub_sta_1:IN(0)", "electricity"],
  ["sub_sta_1:OUT(0)", "xfer_a:IN(0)", "electricity"],
  ["sub_sta_1:OUT(1)", "xfer_b:IN(0)", "electricity"],
  ["sub_sta_1:OUT(2)", "bldg_c_electric:IN(0)", "electricity"],
  ["xfer_a:OUT(0)", "bldg_a_electric:IN(0)", "electricity"],
  ["xfer_b:OUT(0)", "bldg_b_electric:IN(0)", "electricity"],
  ["diesel_resupply:OUT(0)", "fuel_truck:IN(0)", "fuel"],
  ["fuel_truck:OUT(0)", "gen_a:IN(0)", "fuel"],
  ["fuel_truck:OUT(1)", "gen_b:IN(0)", "fuel"],
  ["gen_a:OUT(0)", "xfer_a:IN(1)", "electricity"],
  ["gen_b:OUT(0)", "xfer_b:IN(1)", "electricity"]
]
############## Scenarios #################
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = {type = "fixed", value = 0}
duration = 20
max_occurrences = 1
network = "nw_electric"
calculate_reliability = true
