[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "hours"
max_time = 20
fixed_random = 0.5
############## Loads ###################
[loads.electric_load]
time_unit = "hours"
rate_unit = "kW"
time_rate_pairs = [[0.0, 10.0],[20.0, 0.0]]
############## Components ##############
[components.utility_electrical]
type = "source"
outflow = "electricity"
max_outflow = 30.0
failure_modes = ["grid_outage"]
[components.bldg_a_electric]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "electric_load"
############## Distributions ###########
[cdf.immediately]
type = "fixed"
value = 0
time_unit = "hours"
[cdf.grid_failure]
type = "table" # TODO: change to "quantile_table"
csv_file = "ex19-grid-failure.csv"
[cdf.grid_repair]
type = "table" # TODO: "quantile_table"
csv_file = "ex19-grid-repair.csv"
############# Failure Modes ############
[failure_mode.grid_outage]
failure_cdf = "grid_failure"
repair_cdf = "grid_repair"
############## Networks ################
[networks.nw_electric]
connections = [
  ["utility_electrical:OUT(0)", "bldg_a_electric:IN(0)", "electricity"],
]
############## Scenarios ###############
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = "immediately"
duration = 20
max_occurrences = 1
network = "nw_electric"
calculate_reliability = true
