[meta]
description = "Another Weibull distribution test"

[simulation_info]
input_format_version = "0.2"
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "hours"
max_time = 2

############## Loads ######################
[loads.electric]
time_unit = "hours"
rate_unit = "kW"
time_rate_pairs = [[0.0,100.0],[2.0,0.0]]

[loads.steam]
time_unit = "hours"
rate_unit = "kW"
time_rate_pairs = [[0.0,100.0],[2.0,0.0]]

############## Components #################
#### Loads   ####
[components.elec_load]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "electric"

[components.steam_load]
type = "load"
inflow = "steam"
loads_by_scenario.blue_sky = "steam"

#### Sources ####
[components.electric_utility]
type = "source"
outflow = "electricity"
max_outflow = 20.0

[components.coal_utility]
type = "source"
outflow = "coal"
max_outflow = 15.0

#### Electrical Components ###
[components.transmission]
type = "pass_through"
flow = "electricity"
failure_modes = ["grid_outage"]

[components.substation]
type = "muxer"
flow = "electricity"
num_inflows = 2
num_outflows = 1 

[components.coal_pile]
type = "pass_through"
flow = "coal"
max_outflow = 20.0

[components.boiler]
type = "converter"
inflow = "coal"
outflow = "steam"
constant_efficiency = 0.5

[components.steam_split]
type = "muxer"
flow = "steam"
num_inflows = 1
num_outflows = 2

[components.steam_loop]
type = "muxer"
flow = "steam"
num_inflows = 2
num_outflows = 1

[components.turbine]
type = "converter"
inflow = "steam"
outflow = "electricity"
lossflow = "waste_heat"
constant_efficiency = 0.5

[components.waste_to_steam]
type = "converter"
inflow = "waste_heat"
outflow = "steam"
constant_efficiency = 1

############## dist ###########################
[dist.immediately]
type = "fixed"
value = 0
time_unit = "hours"

[dist.grid_failure]
type = "weibull"
shape = 5
scale = 1473
location = 0
time_unit = "hours"

[dist.grid_repair]
type = "weibull"
shape = 5
scale = 12
location = 0
time_unit = "hours"

############# Failure Modes ############
[failure_mode.grid_outage]
failure_dist = "grid_failure"
repair_dist = "grid_repair"

############## Networks #################
[network]
connections = [
  # Electric Network
  ["electric_utility:OUT(0)", "transmission:IN(0)","electricity"],
  ["transmission:OUT(0)","substation:IN(1)", "electricity"],
  ["substation:OUT(0)", "elec_load:IN(0)", "electricity"],

  #Thermal Network
  ["coal_utility:OUT(0)", "coal_pile:IN(0)","coal"],
  ["coal_pile:OUT(0)","boiler:IN(0)","coal"],
  ["boiler:OUT(0)","steam_split:IN(0)","steam"],
  ["steam_split:OUT(1)","steam_loop:IN(1)","steam"],
  ["turbine:OUT(1)","waste_to_steam:IN(0)","waste_heat"],
  ["waste_to_steam:OUT(0)","steam_loop:IN(0)","steam"],
  ["steam_loop:OUT(0)","steam_load:IN(0)","steam"],

  #Thermal to Electric
  ["steam_split:OUT(0)","turbine:IN(0)","steam"],
  ["turbine:OUT(0)","substation:IN(0)","electricity"],
  ]

############## Scenarios #################
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = "immediately"
duration = 2
max_occurrences = 1
