# Simulation Information
# Very Simple Model @ 2/29/2024 10:37:01 AM
[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "hours"
max_time = 8760
[simulation_info.meta]
id = 4

# Distributions
[dist.immediately]
type = "fixed"
time_unit = "hours"
value = 0.0
[dist.immediately.meta]
id = 32

[dist.substation_electrical_mtbf]
type = "weibull"
time_unit = "hours"
shape = 5.0
scale = 5000.0
location = 0.0
[dist.substation_electrical_mtbf.meta]
id = 33

[dist.substation_electrical_mttr]
type = "fixed"
time_unit = "hours"
value = 24.0
[dist.substation_electrical_mttr.meta]
id = 34

[dist.generator_diesel_engine_mtbf]
type = "weibull"
time_unit = "hours"
shape = 5.0
scale = 70932.0
location = 0.0
[dist.generator_diesel_engine_mtbf.meta]
id = 35

[dist.generator_diesel_engine_mttr]
type = "fixed"
time_unit = "hours"
value = 18.28
[dist.generator_diesel_engine_mttr.meta]
id = 36

[dist.flooding_repair]
type = "normal"
time_unit = "hours"
mean = 144.0
standard_deviation = 10.0
[dist.flooding_repair.meta]
id = 37

[dist.generator_diesel_engine_mtbf_1]
type = "weibull"
time_unit = "hours"
shape = 5.0
scale = 70932.0
location = 0.0
[dist.generator_diesel_engine_mtbf_1.meta]
id = 38

[dist.generator_diesel_engine_mtbf_2]
type = "weibull"
time_unit = "hours"
shape = 5.0
scale = 70932.0
location = 0.0
[dist.generator_diesel_engine_mtbf_2.meta]
id = 39

[dist.chiller_electric_air_cooled_mtbf]
type = "weibull"
time_unit = "hours"
shape = 5.0
scale = 20000.0
location = 0.0
[dist.chiller_electric_air_cooled_mtbf.meta]
id = 103

[dist.chiller_electric_air_cooled_mttr]
type = "fixed"
time_unit = "hours"
value = 72.0
[dist.chiller_electric_air_cooled_mttr.meta]
id = 104

[dist.boiler_mtbf]
type = "weibull"
time_unit = "hours"
shape = 5.0
scale = 51246.0
location = 0.0
[dist.boiler_mtbf.meta]
id = 146

[dist.boiler_mttr]
type = "fixed"
time_unit = "hours"
value = 48.0
[dist.boiler_mttr.meta]
id = 147

# Fragility Modes
[fragility_mode.41_gen_flooding]
fragility_curve = "41_gen_flooding"
repair_dist = "flooding_repair"
[fragility_mode.41_gen_flooding.meta]
id = 6

[fragility_mode.substa_flood]
fragility_curve = "substa_flood"
repair_dist = "flooding_repair"
[fragility_mode.substa_flood.meta]
id = 7

# Fragility Curves
[fragility_curve.41_gen_flooding]
vulnerable_to = "inundation_depth_ft"
type = "linear"
lower_bound = 5.0
upper_bound = 8.0
[fragility_curve.41_gen_flooding.meta]
id = 6

[fragility_curve.substa_flood]
vulnerable_to = "inundation_depth_ft"
type = "linear"
lower_bound = 1.0
upper_bound = 2.0
[fragility_curve.substa_flood.meta]
id = 7

# Failure Modes
[failure_mode.substation_electrical_mtfm]
failure_dist = "substation_electrical_mtbf"
repair_dist = "substation_electrical_mttr"
[failure_mode.substation_electrical_mtfm.meta]
id = 18

[failure_mode.generator_diesel_engine_mtfm]
failure_dist = "generator_diesel_engine_mtbf"
repair_dist = "generator_diesel_engine_mttr"
[failure_mode.generator_diesel_engine_mtfm.meta]
id = 19

[failure_mode.generator_diesel_engine_mtfm_1]
failure_dist = "generator_diesel_engine_mtbf_1"
repair_dist = "generator_diesel_engine_mttr"
[failure_mode.generator_diesel_engine_mtfm_1.meta]
id = 20

[failure_mode.generator_diesel_engine_mtfm_2]
failure_dist = "generator_diesel_engine_mtbf_2"
repair_dist = "generator_diesel_engine_mttr"
[failure_mode.generator_diesel_engine_mtfm_2.meta]
id = 21

[failure_mode.chiller_electric_air_cooled_mtfm]
failure_dist = "chiller_electric_air_cooled_mtbf"
repair_dist = "chiller_electric_air_cooled_mttr"
[failure_mode.chiller_electric_air_cooled_mtfm.meta]
id = 55

[failure_mode.boiler_mtfm]
failure_dist = "boiler_mtbf"
repair_dist = "boiler_mttr"
[failure_mode.boiler_mtfm.meta]
id = 89

# Loads
[loads.41_firehouse_load__electricity]
csv_file = "ex28-electricity.csv"
# #start temp
# time_unit = "hours"
# rate_unit = "kW"
# time_rate_pairs = [
#  [0.0, 73000.0],
#  [8760.0, 0.0],
# ]
# #end temp

[loads.41_firehouse_load__chilled_water]
csv_file = "ex28-chilled-water.csv"
# #start temp
# time_unit = "hours"
# rate_unit = "kW"
# time_rate_pairs = [
#  [0.0, 20.0],
#  [8760.0, 0.0],
# ]
# #end temp

# Components
[components.41_firehouse_load__electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "41_firehouse_load__electricity"
loads_by_scenario.flooding = "41_firehouse_load__electricity"
[components.41_firehouse_load__electricity.meta]
id = 137

[components.41_firehouse_load__chilled_water]
type = "load"
inflow = "chilled_water"
loads_by_scenario.blue_sky = "41_firehouse_load__chilled_water"
loads_by_scenario.flooding = "41_firehouse_load__chilled_water"
[components.41_firehouse_load__chilled_water.meta]
id = 137

[components.substation]
type = "muxer"
dispatch_strategy = "in_order"
flow = "electricity"
num_inflows = 1
num_outflows = 1
fragility_modes = ["substa_flood"]
failure_modes = ["substation_electrical_mtfm"]
[components.substation.meta]
id = 138

[components.ameren_electric_power_utility]
type = "source"
outflow = "electricity"
[components.ameren_electric_power_utility.meta]
id = 139

[components.xfer_switch]
type = "muxer"
dispatch_strategy = "in_order"
flow = "electricity"
num_inflows = 2
num_outflows = 2
[components.xfer_switch.meta]
id = 142

[components.41_generator]
type = "converter"
constant_efficiency = 0.28
inflow = "diesel"
lossflow = "waste_heat"
outflow = "electricity"
fragility_modes = ["41_gen_flooding"]
failure_modes = ["generator_diesel_engine_mtfm_2"]
[components.41_generator.meta]
id = 145

[components.41_bu_fuel_tank_supply]
type = "source"
rate_unit = "kW"
max_outflow = 0
outflow = "diesel"

[components.41_bu_gen_fuel_tank]
type = "store"
capacity = 49_304_000.0   # kJ
capacity_unit = "kJ"
flow = "diesel"
init_soc = 0.5
max_inflow = 87_921_300.0   # kJ
rate_unit = "kW"
max_discharge = 10_000.0 
[components.41_bu_gen_fuel_tank.meta]
id = 146

[components.diesel_fuel_distribution_point]
type = "source"
max_outflow = 1000.0   # kW
outflow = "diesel"
[components.diesel_fuel_distribution_point.meta]
id = 148

[components.chiller]
type = "mover"
cop = 3.05
inflow = "electricity"
outflow = "chilled_water"
failure_modes = ["chiller_electric_air_cooled_mtfm"]
[components.chiller.meta]
id = 1267

# Networks
[network]
connections = [
 ["ameren_electric_power_utility:OUT(0)", "substation:IN(0)", "electricity"],
 ["substation:OUT(0)", "xfer_switch:IN(0)", "electricity"],
 ["xfer_switch:OUT(0)", "41_firehouse_load__electricity:IN(0)", "electricity"],
 ["41_generator:OUT(0)", "xfer_switch:IN(1)", "electricity"],
 ["xfer_switch:OUT(1)", "chiller:IN(0)", "electricity"],
 ["chiller:OUT(0)", "41_firehouse_load__chilled_water:IN(0)", "chilled_water"],
 ["41_bu_gen_fuel_tank:OUT(0)", "41_generator:IN(0)", "diesel"],
 ["41_bu_fuel_tank_supply:OUT(0)", "41_bu_gen_fuel_tank:IN(0)", "diesel"],
]
[network.meta]
id = 4

# Scenarios
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = "immediately"
duration = 8760
max_occurrences = 1
[scenarios.blue_sky.meta]
id = 7

[scenarios.flooding]
time_unit = "hours"
occurrence_distribution = "immediately"
duration = 200
max_occurrences = 1
intensity.inundation_depth_ft = 3.0
[scenarios.flooding.meta]
id = 8
