[meta]
description = """
  Demonstrate table-based efficiency for converter
"""

[simulation_info]
input_format_version = "0.2"
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "h"
max_time = 10.0

[loads.generic_load]
rate_unit = "kW"
time_unit = "h"
time_rate_pairs = [
  [0, 10.0],
  [1, 20.0],
  [2, 30.0],
  [3, 40.0],
  [4, 50.0],
  [5, 100.0],
  [6, 80.0],
  [7, 60.0],
  [8, 40.0],
  [9, 20.0],
  [10, 0.0],
]

[components.natural_gas_source]
type = "source"
rate_unit = "kW"
outflow = "natural_gas"

[components.conv]
type = "variable_efficiency_converter"
inflow = "natural_gas"
outflow = "electricity"
lossflow = "waste_heat"
rate_unit = "kW"
max_outflow = 100.0
efficiency_by_fraction_out = [
  [0.0, 0.20],
  [0.2, 0.25],
  [0.5, 0.30],
  [0.8, 0.32],
  [1.0, 0.28],
]

[components.electrical_load]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "generic_load"

[network]
connections = [
  ["natural_gas_source:OUT(0)", "conv:IN(0)", "natural_gas"],
  ["conv:OUT(0)", "electrical_load:IN(0)", "electricity"],
]

[dist.immediately]
type = "fixed"
value = 0
time_unit = "h"

[scenarios.blue_sky]
duration = 10
time_unit = "h"
occurrence_distribution = "immediately"
max_occurrences = 1
