[simulation_info]
input_format_version = "0.2"
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "hours"
max_time = 4
############################################################
[loads.building1_electrical]
time_unit = "hours"
rate_unit = "kW"
time_rate_pairs = [[0.0,1.0],[4.0,0.0]]

[loads.building2_electrical]
time_unit = "hours"
rate_unit = "kW"
time_rate_pairs = [[0.0,1.0],[4.0,0.0]]
############################################################
[components.utility]
type = "source"
outflow = "electricity"

[components.muxer]
type = "muxer"
group = "group_1"
flow = "electricity"
num_inflows = 1
num_outflows = 2

[components.convA]
type = "converter"
group = "group_1"
inflow = "electricity"
outflow = "electricity"
constant_efficiency = 0.9

[components.batteryA]
type = "store"
group = "group_1"
capacity = 60   # kJ
capacity_unit = "kJ"
flow = "electricity"
init_soc = 1.0
max_charge = 30   # kJ
rate_unit = "kW"
max_discharge = 10.0 

[components.batteryB]
type = "store"
group = "group_1"
capacity = 60   # kJ
capacity_unit = "kJ"
flow = "electricity"
init_soc = 0.5
max_charge = 30   # kJ
rate_unit = "kW"
max_discharge = 10.0 

[components.convB]
type = "converter"
group = "group_1"
inflow = "electricity"
outflow = "electricity"
constant_efficiency = 0.9

[components.loadA]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "building1_electrical"

[components.loadB]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "building2_electrical"

############################################################
[network]
# Specify network as an array of 3-tuples.
# The interpretation is as follows:
# 3-tuples: [COMPONENT_AND_PORT, COMPONENT_AND_PORT, STREAM_ID]
# COMPONENT_AND_PORT := COMPONENT_ID ":" ("IN" | "OUT") "(" \d+ ")" ;
# COMPONENT_ID := STRING_IDENTIFIER ;
# STREAM_ID := STRING_IDENTIFIER ;
# STRING_IDENTIFIER := [a-zA-Z_] [a-zA-Z_0-9]* ;
connections = [
["utility:OUT(0)", "muxer:IN(0)", "electricity"], 
["muxer:OUT(0)", "convA:IN(0)", "electricity"], 
["convA:OUT(0)", "batteryA:IN(0)", "electricity"], 
["batteryA:OUT(0)", "loadA:IN(0)", "electricity"],
["muxer:OUT(1)", "batteryB:IN(0)", "electricity"], 
["batteryB:OUT(0)", "convB:IN(0)", "electricity"], 
["convB:OUT(0)", "loadB:IN(0)", "electricity"]
]
############################################################
[dist.immediately]
type = "fixed"
value = 0
time_unit = "hours"
############################################################
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = "immediately"
duration = 4
max_occurrences = 1
