[simulation_info]
input_format_version = "0.2"
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "hours"
max_time = 4
############################################################
[loads.building_electrical]
time_unit = "hours"
rate_unit = "kW"
time_rate_pairs = [[0.0,200.0],[4.0,0.0]]
############################################################
[components.S_A]
type = "source"
outflow = "electricity"
max_outflow = 100.0
[components.S_B]
type = "source"
outflow = "electricity"
max_outflow = 250.0
[components.SW]
type = "switch"
flow = "electricity"
# initial_state = 0
[components.L]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "building_electrical"
############################################################
[network]
connections = [
  ["S_A:OUT(0)", "SW:IN(0)", "electricity"],
  ["S_B:OUT(0)", "SW:IN(1)", "electricity"],
  ["SW:OUT(0)", "L:IN(0)", "electricity"],
]
############################################################
[dist.immediately]
type = "fixed"
value = 0
time_unit = "hours"
############################################################
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = "immediately"
duration = 4
max_occurrences = 1

