[meta]
description = """
  This example builds on example 40 but also uses:

  * group aggregation
  * disabled component reporting
"""
[simulation_info]
input_format_version = "0.2"
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "d"
max_time = 2
#####################
[loads.building_electrical]
time_unit = "h"
rate_unit = "kW"
time_rate_pairs = [
  [0,187.47],
  [1,146.271],
  [2,137.308],
  [3,170.276],
  [4,139.068],
  [5,171.944],
  [6,140.051],
  [7,173.406],
  [8,127.54],
  [9,135.751],
  [10, 95.195],
  [11, 107.644],
  [12, 81.227],
  [13, 98.928],
  [14, 80.134],
  [15, 97.222],
  [16, 81.049],
  [17, 114.29],
  [18, 102.652],
  [19, 125.672],
  [20, 105.254],
  [21, 125.047],
  [22, 104.824],
  [23, 126.488],
  [24, 107.094],
  [25, 135.559],
  [26, 115.588],
  [27, 137.494],
  [28, 115.386],
  [29, 133.837],
  [30, 113.812],
  [31, 343.795],
  [32, 284.121],
  [33, 295.434],
  [34, 264.364],
  [35, 247.33],
  [36, 235.89],
  [37, 233.43],
  [38, 220.77],
  [39, 213.825],
  [40, 210.726],
  [41, 223.706],
  [42, 219.193],
  [43, 186.31],
  [44, 185.658],
  [45, 173.137],
  [46, 172.236],
  [47, 47.676],
  [48, 48.952],
]
[loads.building_heating]
time_unit = "hours"
rate_unit = "kW"
time_rate_pairs = [
  [0, 29.60017807],
  [1, 16.70505099],
  [2, 16.99812206],
  [3, 23.4456856],
  [4, 17.5842642],
  [5, 23.73875667],
  [6, 17.87733527],
  [7, 24.03182774],
  [8, 17.87733527],
  [9, 23.4456856],
  [10, 16.41197992],
  [11, 18.75654848],
  [12, 14.36048243],
  [13, 16.11890885],
  [14, 10.55055852],
  [15, 13.77434029],
  [16, 9.37827424],
  [17, 13.18819815],
  [18, 9.37827424],
  [19, 13.48126922],
  [20, 9.67134531],
  [21, 12.30898494],
  [22, 10.55055852],
  [23, 13.48126922],
  [24, 9.67134531],
  [25, 13.48126922],
  [26, 12.30898494],
  [27, 14.06741136],
  [28, 12.30898494],
  [29, 13.48126922],
  [30, 10.84362959],
  [31, 4.10299498],
  [32, 45.71908692],
  [33, 38.97845231],
  [34, 33.11703091],
  [35, 26.96253844],
  [36, 24.32489881],
  [37, 22.85954346],
  [38, 26.66946737],
  [39, 29.89324914],
  [40, 26.66946737],
  [41, 24.32489881],
  [42, 27.25560951],
  [43, 26.66946737],
  [44, 22.85954346],
  [45, 21.10111704],
  [46, 18.46347741],
  [47, 0.0],
  [48, 3.22378177],
]
[loads.building_chilled_water]
time_unit = "hours"
rate_unit = "kW"
time_rate_pairs = [
  [0, 219.415919],
  [1, 220.407292],
  [2, 220.407527],
  [3, 219.415979],
  [4, 220.407451],
  [5, 220.407648],
  [6, 220.447532],
  [7, 221.521393],
  [8, 220.61323],
  [9, 220.296692],
  [10, 219.526561],
  [11, 220.407328],
  [12, 220.40751],
  [13, 219.415971],
  [14, 220.407433],
  [15, 220.407631],
  [16, 219.415583],
  [17, 220.407554],
  [18, 220.44675],
  [19, 220.447275],
  [20, 220.447263],
  [21, 220.407465],
  [22, 219.41573],
  [23, 220.407695],
  [24, 220.40752],
  [25, 220.009676],
  [26, 219.813492],
  [27, 220.407526],
  [28, 220.407466],
  [29, 230.717902],
  [30, 231.749028],
  [31, 2529.895654],
  [32, 1359.594387],
  [33, 1205.089133],
  [34, 1117.049434],
  [35, 1090.487092],
  [36, 1560.873117],
  [37, 1188.103825],
  [38, 1179.489328],
  [39, 1160.6685],
  [40, 1090.880605],
  [41, 1273.82897],
  [42, 276.957246],
  [43, 276.957196],
  [44, 254.353283],
  [45, 253.32155],
  [46, 231.709454],
  [47, 220.407697],
  [48, 219.415693],
]
[loads.pv_generation]
time_unit = "hours"
rate_unit = "kW"
time_rate_pairs = [
  [0, 0.0],
  [1, 0.0],
  [2, 0.0],
  [3, 0.0],
  [4, 0.0],
  [5, 0.0],
  [6, 0.0],
  [7, 14.36],
  [8, 671.759],
  [9, 1265.933],
  [10, 1583.21],
  [11, 1833.686],
  [12, 1922.872],
  [13, 1749.437],
  [14, 994.715],
  [15, 468.411],
  [16, 0.0],
  [17, 0.0],
  [18, 0.0],
  [19, 0.0],
  [20, 0.0],
  [21, 0.0],
  [22, 0.0],
  [23, 0.0],
  [24, 0.0],
  [25, 0.0],
  [26, 0.0],
  [27, 0.0],
  [28, 0.0],
  [29, 0.0],
  [30, 0.0],
  [31, 10.591],
  [32, 693.539],
  [33, 1191.017],
  [34, 1584.868],
  [35, 1820.692],
  [36, 1952.869],
  [37, 1799.1],
  [38, 1067.225],
  [39, 396.023],
  [40, 0.0],
  [41, 0.0],
  [42, 0.0],
  [43, 0.0],
  [44, 0.0],
  [45, 0.0],
  [46, 0.0],
  [47, 0.0],
  [48, 0.0],
]
#####################
[components.electric_utility]
type = "source"
outflow = "electricity"
max_outflow = 100.0
[components.pv_array]
type = "uncontrolled_source"
group = "elec_group"
outflow = "electricity"
supply_by_scenario.blue_sky = "pv_generation"
supply_by_scenario.hurricane = "pv_generation"
[components.natural_gas_utility]
type = "source"
outflow = "natural_gas"
report = false
max_outflow = 1000.0
[components.natural_gas_turbine]
type = "variable_efficiency_converter"
group = "gas_group"
report = false
inflow = "natural_gas"
outflow = "electricity"
lossflow = "heating"
rate_unit = "kW"
max_outflow = 500.0
efficiency_by_fraction_out = [
  [0.0, 0.20],
  [0.2, 0.25],
  [0.5, 0.45],
  [0.8, 0.64],
  [1.0, 0.52],
]
[components.diesel_fuel_tank]
type = "store"
group = "diesel_group"
report = false
flow = "diesel"
rate_unit = "kW"
max_outflow = 20.0
capacity_unit = "kWh"
capacity = 4000.0
max_charge = 10.0
max_discharge = 20.0
[components.backup_generator]
type = "converter"
group = "elec_group"
report = false
inflow = "diesel"
outflow = "electricity"
lossflow = "waste_heat"
constant_efficiency = 0.3
[components.power_lines]
type = "pass_through"
group = "elec_group"
flow = "electricity"
[components.backup_chiller]
type = "mover"
group = "cool_group"
report = false
inflow = "electricity"
outflow = "chilled_water"
cop = 2.5
[components.main_chiller]
type = "variable_efficiency_mover"
group = "cool_group"
report = false
inflow = "electricity"
outflow = "chilled_water"
rate_unit = "kW"
max_outflow = 100.0
cop_by_fraction_out = [
  [0.0, 2.7],
  [0.2, 3.2],
  [0.5, 3.7],
  [0.8, 4.2],
  [1.0, 3.8],
]
[components.chilled_water_junction]
type = "mux"
group = "cool_group"
report = false
flow = "chilled_water"
num_inflows = 2
num_outflows = 1
[components.heating_manifold]
type = "mux"
group = "heat_group"
report = false
flow = "heating"
num_inflows = 3
num_outflows = 1
[components.electric_bus0]
type = "mux"
group = "elec_group"
flow = "electricity"
num_inflows = 1
num_outflows = 2
[components.electric_bus1]
type = "mux"
group = "elec_group"
flow = "electricity"
num_inflows = 4
num_outflows = 4
[components.ng_fired_heater]
type = "converter"
group = "gas_group"
report = false
inflow = "natural_gas"
outflow = "heating"
lossflow = "waste_heat"
constant_efficiency = 0.94
[components.diesel_fired_heater]
type = "converter"
group = "heat_group"
report = false
inflow = "diesel"
outflow = "heating"
lossflow = "waste_heat"
constant_efficiency = 0.88
[components.diesel_fuel_router]
type = "mux"
group = "diesel_group"
report = false
flow = "diesel"
num_inflows = 1
num_outflows = 2
[components.ng_fuel_router]
type = "mux"
group = "gas_group"
report = false
flow = "natural_gas"
num_inflows = 1
num_outflows = 2
[components.battery]
type = "store"
group = "elec_group"
flow = "electricity"
capacity = 20.0
capacity_unit = "kWh"
charge_at_soc = 0.8
init_soc = 1.0
max_charge = 5.0
max_discharge = 20.0
roundtrip_efficiency = 0.9
[components.automated_transfer_switch]
type = "switch"
group = "elec_group"
flow = "electricity"
[components.building_electrical]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "building_electrical"
loads_by_scenario.hurricane = "building_electrical"
[components.building_heating]
type = "load"
inflow = "heating"
loads_by_scenario.blue_sky = "building_heating"
loads_by_scenario.hurricane = "building_heating"
[components.building_cooling]
type = "load"
inflow = "chilled_water"
loads_by_scenario.blue_sky = "building_chilled_water"
loads_by_scenario.hurricane = "building_chilled_water"
[components.electric_pump]
type = "constant_load"
inflow = "electricity"
constant_request = 10.0
#####################
[dist.immediately]
type = "fixed"
value = 0
time_unit = "hours"
#####################
[network]
connections = [
  # Electricity
  ["electric_utility:OUT(0)", "automated_transfer_switch:IN(0)", "electricity"],
  ["pv_array:OUT(0)", "electric_bus0:IN(0)", "electricity"],
  ["electric_bus0:OUT(0)", "battery:IN(0)", "electricity"],
  ["electric_bus0:OUT(1)", "electric_bus1:IN(0)", "electricity"],
  ["battery:OUT(0)", "automated_transfer_switch:IN(1)", "electricity"],
  ["automated_transfer_switch:OUT(0)", "electric_bus1:IN(1)", "electricity"],
  ["natural_gas_turbine:OUT(0)", "electric_bus1:IN(2)", "electricity"],
  ["backup_generator:OUT(0)", "electric_bus1:IN(3)", "electricity"],
  ["electric_bus1:OUT(0)", "power_lines:IN(0)", "electricity"],
  ["power_lines:OUT(0)", "building_electrical:IN(0)", "electricity"],
  ["electric_bus1:OUT(1)", "main_chiller:IN(0)", "electricity"],
  ["electric_bus1:OUT(2)", "backup_chiller:IN(0)", "electricity"],
  ["electric_bus1:OUT(3)", "electric_pump:IN(0)", "electricity"],
  # Natural Gas
  ["natural_gas_utility:OUT(0)", "ng_fuel_router:IN(0)", "natural_gas"],
  ["ng_fuel_router:OUT(0)", "natural_gas_turbine:IN(0)", "natural_gas"],
  ["ng_fuel_router:OUT(1)", "ng_fired_heater:IN(0)", "natural_gas"],
  # Diesel
  ["diesel_fuel_tank:OUT(0)", "diesel_fuel_router:IN(0)", "diesel"],
  ["diesel_fuel_router:OUT(0)", "backup_generator:IN(0)", "diesel"],
  ["diesel_fuel_router:OUT(1)", "diesel_fired_heater:IN(0)", "diesel"],
  # Heating
  ["natural_gas_turbine:OUT(1)", "heating_manifold:IN(0)", "heating"],
  ["ng_fired_heater:OUT(0)", "heating_manifold:IN(1)", "heating"],
  ["diesel_fired_heater:OUT(0)", "heating_manifold:IN(2)", "heating"],
  ["heating_manifold:OUT(0)", "building_heating:IN(0)", "heating"],
  # Chilled Water
  ["main_chiller:OUT(0)", "chilled_water_junction:IN(0)", "chilled_water"],
  ["backup_chiller:OUT(0)", "chilled_water_junction:IN(1)", "chilled_water"],
  ["chilled_water_junction:OUT(0)", "building_cooling:IN(0)", "chilled_water"],
]
#####################
[scenarios.blue_sky]
time_unit = "d"
occurrence_distribution = "immediately"
duration = 2
max_occurrences = 1
[scenarios.hurricane]
time_unit = "d"
occurrence_distribution = "immediately"
duration = 2
max_occurrences = 1
