############################################################
# Simulation Information
[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "years"
max_time = 1000
############################################################
# Loads
[loads.building_electrical]
csv_file = "ex03.csv"
############################################################
# Components
[components.electric_utility]
type = "source"
outflow = "electricity"
fragility_modes = ["highly_vulnerable_to_wind"]
max_outflow = 10.0
[components.cluster_01_electric]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "building_electrical"
loads_by_scenario.class_1_hurricane = "building_electrical"
loads_by_scenario.class_4_hurricane = "building_electrical"
loads_by_scenario.class_5_hurricane = "building_electrical"
fragility_modes = ["somewhat_vulnerable_to_flooding"]
[components.emergency_generator]
type = "source"
outflow = "electricity"
fragility_modes = ["somewhat_vulnerable_to_flooding"]
[components.bus]
type = "muxer"
flow = "electricity"
num_inflows = 2
num_outflows = 1
# An "in_order" dispatch strategy means that power requests are routed in order
# upstream through the input ports in the order they are specified. That is,
# "inflow_grid" would be asked to provide power first. If there is any lack of
# power, "inflow_genset" would be asked to make up the difference. Note: on
# the output side, if more than one output, outputs are handled differently in
# that power shortages are always spread evenly across all outputs. Explicit
# switches or changes in load requests are used to drop loads (or simulate
# their dropping).
dispatch_strategy = "in_order"
fragility_modes = ["highly_vulnerable_to_wind", "somewhat_vulnerable_to_flooding"]
############################################################
# Fragility Modes
[fragility_mode.somewhat_vulnerable_to_flooding]
fragility_curve = "somewhat_vulnerable_to_flooding_curve"
[fragility_mode.highly_vulnerable_to_wind]
fragility_curve = "highly_vulnerable_to_wind_curve"
############################################################
# Fragility Curves
[fragility_curve.somewhat_vulnerable_to_flooding_curve]
vulnerable_to = "inundation_depth_ft"
type = "linear"
lower_bound = 6.0
upper_bound = 14.0
[fragility_curve.highly_vulnerable_to_wind_curve]
vulnerable_to = "wind_speed_mph"
type = "linear"
lower_bound = 80.0
upper_bound = 160.0
############################################################
# Networks
[network]
connections = [
  ["electric_utility:OUT(0)", "bus:IN(0)", "electricity"],
  ["emergency_generator:OUT(0)", "bus:IN(1)", "electricity"],
  ["bus:OUT(0)", "cluster_01_electric:IN(0)", "electricity"]]
############################################################
# Distributions
[dist.immediately]
type = "fixed"
value = 0
time_unit = "hours"
[dist.every_10_years]
type = "fixed"
value = 87600
time_unit = "hours"
############################################################
# Scenarios
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = "immediately"
duration = 8760
max_occurrences = 1
network = "normal_operations"
[scenarios.class_4_hurricane]
time_unit = "hours"
occurrence_distribution = "every_10_years"
duration = 336
max_occurrences = "unlimited"
network = "emergency_operations"
intensity.wind_speed_mph = 156
intensity.inundation_depth_ft = 8
[scenarios.class_5_hurricane]
time_unit = "hours"
occurrence_distribution = "every_10_years"
duration = 336
max_occurrences = "unlimited"
network = "emergency_operations"
intensity.wind_speed_mph = 200 # force failure deterministically
intensity.inundation_depth_ft = 20 # force failure deterministically
[scenarios.class_1_hurricane]
time_unit = "hours"
occurrence_distribution = "every_10_years"
duration = 336
max_occurrences = "unlimited"
network = "emergency_operations"
intensity.wind_speed_mph = 74 # force survival deterministically
intensity.inundation_depth_ft = 2 # force survival deterministically
