[meta]
description = "exercise the store components"
[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "hours"
max_time = 20
############################################################
[loads.building_electrical]
time_unit = "hours"
rate_unit = "kW"
time_rate_pairs = [[0.0,1.0],[20.0,0.0]]
############################################################
[components.electric_source_A]
type = "source"
max_outflow = 0.0
outflow = "electricity"
[components.electric_source_B]
type = "source"
max_outflow = 0.0
outflow = "electricity"
[components.electric_battery_A]
type = "store"
flow = "electricity"
capacity_unit = "kWh"
capacity = 10.0
max_inflow = 1.0
init_soc = 1.0
max_discharge = 1.0
[components.electric_battery_B]
type = "store"
flow = "electricity"
capacity_unit = "kWh"
capacity = 10.0
max_inflow = 1.0
init_soc = 0.5
max_discharge = 1.0
[components.electric_load_A]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "building_electrical"
[components.electric_load_B]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "building_electrical"
############################################################
[network]
connections = [
  ["electric_source_A:OUT(0)", "electric_battery_A:IN(0)", "electricity"],
  ["electric_battery_A:OUT(0)", "electric_load_A:IN(0)", "electricity"],
  ["electric_source_B:OUT(0)", "electric_battery_B:IN(0)", "electricity"],
  ["electric_battery_B:OUT(0)", "electric_load_B:IN(0)", "electricity"],
  ]
############################################################
[dist.immediately]
type = "fixed"
value = 0
time_unit = "hours"
############################################################
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = "immediately"
duration = 20
max_occurrences = 1
