############################################################
# Simulation Information
[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "years"
max_time = 100
fixed_random = 0.4
############################################################
# Loads
[loads.building_electrical]
time_unit = "hours"
rate_unit = "kW"
time_rate_pairs = [
  [0.0, 1.0],
  [1200.0, 10.0],
  [2400.0, 1.0],
  [3600.0, 0.0],
]
############################################################
# Components
[components.electric_utility]
type = "source"
outflow = "electricity"
fragility_modes = ["highly_vulnerable_to_wind"]
rate_unit = "kW"
max_outflow = 10.0
[components.cluster_01_electric]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "building_electrical"
loads_by_scenario.class_1_hurricane = "building_electrical"
loads_by_scenario.class_4_hurricane = "building_electrical"
loads_by_scenario.class_5_hurricane = "building_electrical"
[components.emergency_generator]
type = "source"
outflow = "electricity"
fragility_modes = ["somewhat_vulnerable_to_flooding"]
[components.bus]
type = "muxer"
flow = "electricity"
num_inflows = 2
num_outflows = 1
fragility_modes = [
  "highly_vulnerable_to_wind",
  "somewhat_vulnerable_to_flooding",
  ]
############################################################
# Fragility Modes
[fragility_mode.somewhat_vulnerable_to_flooding]
fragility_curve = "somewhat_vulnerable_to_flooding_curve"
[fragility_mode.highly_vulnerable_to_wind]
fragility_curve = "highly_vulnerable_to_wind_curve"
############################################################
# Fragility Curves
[fragility_curve.somewhat_vulnerable_to_flooding_curve]
vulnerable_to = "inundation_depth_ft"
type = "tabular"
intensity_failure_pairs = [
  [6.0, 0.0],
  [14.0, 1.0],
]
[fragility_curve.highly_vulnerable_to_wind_curve]
vulnerable_to = "wind_speed_mph"
type = "tabular"
intensity_failure_pairs = [
  [80.0, 0.0],
  [160.0, 1.0],
]
############################################################
# Network
[network]
connections = [
  ["electric_utility:OUT(0)", "bus:IN(0)", "electricity"],
  ["emergency_generator:OUT(0)", "bus:IN(1)", "electricity"],
  ["bus:OUT(0)", "cluster_01_electric:IN(0)", "electricity"],
  ]
############################################################
# Distributions
[dist.immediately]
type = "fixed"
value = 0
time_unit = "hours"
[dist.every_10_years]
type = "fixed"
value = 87600
time_unit = "hours"
############################################################
# Scenarios
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = "immediately"
duration = 8760
max_occurrences = 1
[scenarios.class_4_hurricane]
time_unit = "hours"
occurrence_distribution = "every_10_years"
duration = 336
max_occurrences = "unlimited"
intensity.wind_speed_mph = 156
intensity.inundation_depth_ft = 8
[scenarios.class_5_hurricane]
time_unit = "hours"
occurrence_distribution = "every_10_years"
duration = 336
max_occurrences = "unlimited"
intensity.wind_speed_mph = 200 # force failure deterministically
intensity.inundation_depth_ft = 20 # force failure deterministically
[scenarios.class_1_hurricane]
time_unit = "hours"
occurrence_distribution = "every_10_years"
duration = 336
max_occurrences = "unlimited"
intensity.wind_speed_mph = 74 # force survival deterministically
intensity.inundation_depth_ft = 2 # force survival deterministically
