

############################################################
# General Simulation Information
[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "years"
max_time = 100 # ...
############################################################
# Load Profiles
[loads.b1_heat_removed_uncontrolled_s1]
csv_file = "s1_b1_cooling.csv"
[loads.environment_heat_removed_s1]
csv_file = "s1_environment_heat_sink.csv"
############################################################
# Components
[components.utility_electricity_source]
type = "source"
outflow = "electricity"
[components.b1_heat_removed_uncontrolled]
type = "uncontrolled_source"
outflow = "heat_removed"
supply_by_scenario.s1 = "b1_heat_removed_uncontrolled_s1"
[components.environment_heat_removed]
type = "load"
inflow = "heat_removed"
loads_by_scenario.s1 = "environment_heat_removed_s1"
[components.b1_heat_removed_mover]
type = "mover"
inflow0 = "heat_removed"
inflow1 = "electricity"
outflow = "heat_removed"
COP = 5.0 # ...
############################################################
# Fragility Curves
############################################################
# Distributions
[dist.every_30_years]
type = "fixed"
value = 262800.0 # ...
time_unit = "hours"
############################################################
# Failure Modes
############################################################
# Networks
[networks.nw]
connections = [
  ["b1_heat_removed_mover:OUT(0)", "environment_heat_removed:IN(0)", "heat_removed"],
  ["b1_heat_removed_uncontrolled:OUT(0)", "b1_heat_removed_mover:IN(0)", "heat_removed"],
  ["utility_electricity_source:OUT(0)", "b1_heat_removed_mover:IN(1)", "electricity"],
  ]
############################################################
# Scenarios
[scenarios.s1]
time_unit = "hours"
occurrence_distribution = "every_30_years"
duration = 336 # ...
max_occurrences = -1 # ...
calculate_reliability = false
network = "nw"
