#!/bin/bash
date
if ! cmake -DERIN_TESTING=ON -DDO_DEBUG_PRINT=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..; then
  echo CMAKE CALL FAILED!
  exit 1
fi
if !  cmake --build . -j 4; then
  echo BUILD FAILED!
  exit 1
fi
if ! ctest --output-on-failure; then
  echo CTEST FAILED!
  exit 1
fi
echo Running Regressions Suite...
if ! ruby ../scripts/regression_test.rb; then
  echo REGRESSIONS FOUND!
  exit 1
fi
time ./bin/str8760
mkdir -p tidy
echo Running Clang Tidy...
clang-tidy -p compile_commands.json -header-filter=.* ../include/erin/erin.h > tidy/erin.h.txt
clang-tidy -p compile_commands.json -header-filter=.* ../src/cli.cpp > tidy/cli.cpp.txt
clang-tidy -p compile_commands.json -header-filter=.* ../src/debug_utils.h > tidy/debug_utils.h.txt
clang-tidy -p compile_commands.json -header-filter=.* ../src/erin.cpp > tidy/erin.cpp.txt
clang-tidy -p compile_commands.json -header-filter=.* ../src/erin_csv.h > tidy/erin_csv.h.txt
clang-tidy -p compile_commands.json -header-filter=.* ../src/erin_generics.h > tidy/erin_generics.h.txt
clang-tidy -p compile_commands.json -header-filter=.* ../src/limits.cpp > tidy/limits.cpp.txt
clang-tidy -p compile_commands.json -header-filter=.* ../src/stress_test_8760.cpp > tidy/stress_test_8760.cpp.txt
clang-tidy -p compile_commands.json -header-filter=.* ../src/stress_test_8760x5000.cpp > tidy/stress_test_8760x5000.cpp.txt
clang-tidy -p compile_commands.json -header-filter=.* ../test/erin_test_utils.h > tidy/erin_test_utils.h.txt
clang-tidy -p compile_commands.json -header-filter=.* ../test/erin_tests.cpp > tidy/erin_tests.cpp.txt
echo Done!
