[repeat_file]
filename = "1_hotel__chilled_water.csv"
num_to_read = 64

[mixed_file]
filename = "1_mixed.csv"

[multi_files]
filenames = [
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv"
]

