[repeat_file]
filename = "1_hotel__chilled_water.csv"
num_to_read = 1280

[mixed_file]
filename = "1_mixed.csv"
num_to_read = 20

[multi_files]
filenames = [
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv",
"1_hotel__chilled_water.csv"
]
num_to_read = 10

