

############################################################
# General Simulation Information
[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "years"
max_time = 100 # ...
############################################################
# Load Profiles
[loads.b1_electricity_s1]
csv_file = "s1_b1_electricity.csv"
############################################################
# Components
[components.utility_electricity_source]
type = "source"
outflow = "electricity"
fragility_modes = ["highly_vulnerable_to_wind"]
[components.b1_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.s1 = "b1_electricity_s1"
############################################################
# Fragility Modes
[fragility_mode.highly_vulnerable_to_wind]
fragility_curve = "highly_vulnerable_to_wind_curve"
############################################################
# Fragility Curves
[fragility_curve.highly_vulnerable_to_wind_curve]
vulnerable_to = "wind_speed_mph"
type = "linear"
lower_bound = 80.0 # ...
upper_bound = 160.0 # ...
############################################################
# Distributions
[dist.every_30_years]
type = "fixed"
value = 262800.0 # ...
time_unit = "hours"
############################################################
# Failure Modes
############################################################
# Networks
[networks.nw]
connections = [
  ["utility_electricity_source:OUT(0)", "b1_electricity:IN(0)", "electricity"],
  ]
############################################################
# Scenarios
[scenarios.s1]
time_unit = "hours"
occurrence_distribution = "every_30_years"
duration = 336 # ...
max_occurrences = -1 # ...
calculate_reliability = false
network = "nw"
intensity.wind_speed_mph = 150.0 # ...
intensity.inundation_depth_ft = 12.0 # ...
