

############################################################
# General Simulation Information
[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "years"
max_time = 100 # ...
############################################################
# Load Profiles
[loads.b1_electricity_s1]
csv_file = "s1_b1_electricity.csv"
############################################################
# Components
[components.utility_electricity_source]
type = "source"
outflow = "electricity"
[components.b1_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.s1 = "b1_electricity_s1"
[components.utility_to_b1_electricity_inflow_bus]
type = "muxer"
stream = "electricity"
num_inflows = 1 # ...
num_outflows = 2 # ...
dispatch_strategy = "in_order"
[components.utility_to_b1_electricity_outflow_bus]
type = "muxer"
stream = "electricity"
num_inflows = 2 # ...
num_outflows = 1 # ...
dispatch_strategy = "in_order"
[components.electric_lines_A]
type = "pass_through"
stream = "electricity"
[components.electric_lines_B]
type = "pass_through"
stream = "electricity"
############################################################
# Fragility Curves
############################################################
# Distributions
[dist.every_30_years]
type = "fixed"
value = 262800 # ...
time_unit = "hours"
############################################################
# Failure Modes
############################################################
# Networks
[networks.nw]
connections = [
  ["electric_lines_A:OUT(0)", "utility_to_b1_electricity_outflow_bus:IN(0)", "electricity"],
  ["electric_lines_B:OUT(0)", "utility_to_b1_electricity_outflow_bus:IN(1)", "electricity"],
  ["utility_electricity_source:OUT(0)", "utility_to_b1_electricity_inflow_bus:IN(0)", "electricity"],
  ["utility_to_b1_electricity_inflow_bus:OUT(0)", "electric_lines_A:IN(0)", "electricity"],
  ["utility_to_b1_electricity_inflow_bus:OUT(1)", "electric_lines_B:IN(0)", "electricity"],
  ["utility_to_b1_electricity_outflow_bus:OUT(0)", "b1_electricity:IN(0)", "electricity"],
  ]
############################################################
# Scenarios
[scenarios.s1]
time_unit = "hours"
occurrence_distribution = "every_30_years"
duration = 336 # ...
max_occurrences = -1 # ...
calculate_reliability = false
network = "nw"
