
[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "years"
max_time = 100
############################################################
[loads.mc_electricity_blue_sky]
csv_file = "mc_blue_sky_electricity.csv"
[loads.other_electricity_blue_sky]
csv_file = "other_blue_sky_electricity.csv"
############################################################
[components.electricity_source]
type = "source"
outflow = "electricity"
[components.natural_gas_source]
type = "source"
outflow = "natural_gas"
[components.building_level_electric_bus]
type = "muxer"
stream = "electricity"
num_inflows = 1
num_outflows = 2
dispatch_strategy = "in_order"
[components.mc_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "mc_electricity_blue_sky"
[components.other_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "other_electricity_blue_sky"
[components.mc_electric_generator]
type = "converter"
inflow = "natural_gas"
outflow = "electricity"
lossflow = "waste_heat"
constant_efficiency = 0.42
[components.mc_electric_bus]
type = "muxer"
stream = "electricity"
num_inflows = 2
num_outflows = 1
dispatch_strategy = "in_order"
############################################################
[networks.nw]
connections = [
  ["electricity_source:OUT(0)", "building_level_electric_bus:IN(0)", "electricity"],
  ["building_level_electric_bus:OUT(0)", "mc_electric_bus:IN(0)", "electricity"],
  ["mc_electric_generator:OUT(0)", "mc_electric_bus:IN(1)", "electricity"],
  ["natural_gas_source:OUT(0)", "mc_electric_generator:IN(0)", "natural_gas"],
  ["building_level_electric_bus:OUT(1)", "other_electricity:IN(0)", "electricity"],
  ]
############################################################
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = {type = "fixed", value = 0, time_unit="hours"}
duration = 8760
max_occurrences = 1
network = "nw"
