

############################################################
# General Simulation Information
[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "years"
max_time = 100 # ...
############################################################
# Load Profiles
[loads.b1_electricity_s1]
csv_file = "s1_b1_electricity.csv"
############################################################
# Components
[components.utility_electricity_source]
type = "source"
outflow = "electricity"
failure_modes = ["typical_utility_failures"]
[components.b1_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.s1 = "b1_electricity_s1"
############################################################
# Fragility Curves
############################################################
# Distributions
[dist.every_30_years]
type = "fixed"
value = 262800.0 # ...
time_unit = "hours"
[dist.every_10_hours]
type = "fixed"
value = 10.0 # ...
time_unit = "hours"
[dist.every_4_years]
type = "fixed"
value = 35040.0 # ...
time_unit = "hours"
############################################################
# Failure Modes
[failure_mode.typical_utility_failures]
failure_dist = "every_10_hours"
repair_dist = "every_4_years"
############################################################
# Networks
[networks.nw]
connections = [
  ["utility_electricity_source:OUT(0)", "b1_electricity:IN(0)", "electricity"],
  ]
############################################################
# Scenarios
[scenarios.s1]
time_unit = "hours"
occurrence_distribution = "every_30_years"
duration = 336 # ...
max_occurrences = -1 # ...
calculate_reliability = false
network = "nw"
