
[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "years"
max_time = 100 # ...
############################################################
[loads.mc_electricity_blue_sky]
csv_file = "mc_blue_sky_electricity.csv"
[loads.other_electricity_blue_sky]
csv_file = "other_blue_sky_electricity.csv"
[loads.mc_heating_blue_sky]
csv_file = "mc_blue_sky_heating.csv"
[loads.other_heating_blue_sky]
csv_file = "other_blue_sky_heating.csv"
############################################################
[components.mc_electric_generator]
type = "converter"
inflow = "natural_gas"
outflow = "electricity"
lossflow = "waste_heat"
constant_efficiency = 0.32
[components.mc_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "mc_electricity_blue_sky"
[components.mc_electricity_bus]
type = "muxer"
stream = "electricity"
num_inflows = 2
num_outflows = 1
dispatch_strategy = "in_order"
[components.mc_gas_boiler]
type = "converter"
inflow = "natural_gas"
outflow = "heating"
lossflow = "waste_heat"
constant_efficiency = 0.85
[components.mc_heating]
type = "load"
inflow = "heating"
loads_by_scenario.blue_sky = "mc_heating_blue_sky"
[components.mc_heating_bus]
type = "muxer"
stream = "heating"
num_inflows = 2
num_outflows = 1
dispatch_strategy = "in_order"
[components.mc_natural_gas_bus]
type = "muxer"
stream = "natural_gas"
num_inflows = 1
num_outflows = 2
dispatch_strategy = "in_order"
[components.mc_thermal_storage]
type = "store"
outflow = "heating"
inflow = "heating"
capacity_unit = "kWh"
capacity = 100.0
max_inflow = 10.0
[components.other_electric_generator]
type = "converter"
inflow = "natural_gas"
outflow = "electricity"
lossflow = "waste_heat"
constant_efficiency = 0.32
[components.other_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "other_electricity_blue_sky"
[components.other_electricity_bus]
type = "muxer"
stream = "electricity"
num_inflows = 2
num_outflows = 1
dispatch_strategy = "in_order"
[components.other_gas_boiler]
type = "converter"
inflow = "natural_gas"
outflow = "heating"
lossflow = "waste_heat"
constant_efficiency = 0.85
[components.other_heating]
type = "load"
inflow = "heating"
loads_by_scenario.blue_sky = "other_heating_blue_sky"
[components.other_heating_bus]
type = "muxer"
stream = "heating"
num_inflows = 2
num_outflows = 1
dispatch_strategy = "in_order"
[components.other_natural_gas_bus]
type = "muxer"
stream = "natural_gas"
num_inflows = 1
num_outflows = 2
dispatch_strategy = "in_order"
[components.other_thermal_storage]
type = "store"
outflow = "heating"
inflow = "heating"
capacity_unit = "kWh"
capacity = 100.0
max_inflow = 10.0
[components.utility_electricity_bus]
type = "muxer"
stream = "electricity"
num_inflows = 1
num_outflows = 2
dispatch_strategy = "in_order"
[components.utility_electricity_source]
type = "source"
outflow = "electricity"
[components.utility_heating_bus]
type = "muxer"
stream = "heating"
num_inflows = 1
num_outflows = 2
dispatch_strategy = "in_order"
[components.utility_heating_source]
type = "source"
outflow = "heating"
[components.utility_natural_gas_bus]
type = "muxer"
stream = "natural_gas"
num_inflows = 1
num_outflows = 2
dispatch_strategy = "in_order"
[components.utility_natural_gas_source]
type = "source"
outflow = "natural_gas"
############################################################
[networks.nw]
connections = [
  ["mc_electric_generator:OUT(0)", "mc_electricity_bus:IN(1)", "electricity"],
  ["mc_electricity_bus:OUT(0)", "mc_electricity:IN(0)", "electricity"],
  ["other_electric_generator:OUT(0)", "other_electricity_bus:IN(1)", "electricity"],
  ["other_electricity_bus:OUT(0)", "other_electricity:IN(0)", "electricity"],
  ["utility_electricity_bus:OUT(0)", "mc_electricity_bus:IN(0)", "electricity"],
  ["utility_electricity_bus:OUT(1)", "other_electricity_bus:IN(0)", "electricity"],
  ["utility_electricity_source:OUT(0)", "utility_electricity_bus:IN(0)", "electricity"],
  ["mc_natural_gas_bus:OUT(0)", "mc_electric_generator:IN(0)", "natural_gas"],
  ["mc_natural_gas_bus:OUT(1)", "mc_gas_boiler:IN(0)", "natural_gas"],
  ["other_natural_gas_bus:OUT(0)", "other_electric_generator:IN(0)", "natural_gas"],
  ["other_natural_gas_bus:OUT(1)", "other_gas_boiler:IN(0)", "natural_gas"],
  ["utility_natural_gas_bus:OUT(0)", "mc_natural_gas_bus:IN(0)", "natural_gas"],
  ["utility_natural_gas_bus:OUT(1)", "other_natural_gas_bus:IN(0)", "natural_gas"],
  ["utility_natural_gas_source:OUT(0)", "utility_natural_gas_bus:IN(0)", "natural_gas"],
  ["mc_gas_boiler:OUT(0)", "mc_heating_bus:IN(1)", "heating"],
  ["mc_heating_bus:OUT(0)", "mc_heating:IN(0)", "heating"],
  ["mc_thermal_storage:OUT(0)", "mc_heating_bus:IN(0)", "heating"],
  ["other_gas_boiler:OUT(0)", "other_heating_bus:IN(1)", "heating"],
  ["other_heating_bus:OUT(0)", "other_heating:IN(0)", "heating"],
  ["other_thermal_storage:OUT(0)", "other_heating_bus:IN(0)", "heating"],
  ["utility_heating_bus:OUT(0)", "mc_thermal_storage:IN(0)", "heating"],
  ["utility_heating_bus:OUT(1)", "other_thermal_storage:IN(0)", "heating"],
  ["utility_heating_source:OUT(0)", "utility_heating_bus:IN(0)", "heating"],
  ]
############################################################
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = {type = "fixed", value = 0, time_unit="hours"}
duration = 8760 # ...
max_occurrences = 1 # ...
network = "nw"
