
[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "years"
max_time = 100
############################################################
[loads.mc_electricity_blue_sky]
csv_file = "mc_blue_sky_electricity.csv"
[loads.other_electricity_blue_sky]
csv_file = "other_blue_sky_electricity.csv"
############################################################
[components.electric_source]
type = "source"
outflow = "electricity"
[components.building_level_electric_bus]
type = "muxer"
stream = "electricity"
num_inflows = 1
num_outflows = 2
[components.mc_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "mc_electricity_blue_sky"
[components.other_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "other_electricity_blue_sky"
############################################################
[networks.nw]
connections = [
  ["electric_source:OUT(0)", "building_level_electric_bus:IN(0)", "electricity"],
  ["building_level_electric_bus:OUT(0)", "mc_electricity_load:IN(0)", "electricity"],
  ["building_level_electric_bus:OUT(1)", "other_electricity_load:IN(0)", "electricity"],
  ]
############################################################
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = {type = "fixed", value = 0, time_unit="hours"}
duration = 8760
max_occurrences = 1
network = "nw"

