
[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "years"
max_time = 100 # ...
############################################################
[loads.mc_electricity_blue_sky]
csv_file = "mc_blue_sky_electricity.csv"
[loads.other_electricity_blue_sky]
csv_file = "other_blue_sky_electricity.csv"
[loads.mc_electricity_s1]
csv_file = "mc_s1_electricity.csv"
[loads.other_electricity_s1]
csv_file = "other_s1_electricity.csv"
[loads.mc_electricity_s2]
csv_file = "mc_s2_electricity.csv"
[loads.other_electricity_s2]
csv_file = "other_s2_electricity.csv"
############################################################
[components.mc_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "mc_electricity_blue_sky"
loads_by_scenario.s1 = "mc_electricity_s1"
loads_by_scenario.s2 = "mc_electricity_s2"

[components.other_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "other_electricity_blue_sky"
loads_by_scenario.s1 = "other_electricity_s1"
loads_by_scenario.s2 = "other_electricity_s2"

[components.utility_electricity_bus]
type = "muxer"
stream = "electricity"
num_inflows = 1
num_outflows = 2
dispatch_strategy = "in_order"

[components.utility_electricity_source]
type = "source"
outflow = "electricity"

############################################################
[networks.nw]
connections = [
  ["utility_electricity_bus:OUT(0)", "mc_electricity:IN(0)", "electricity"],
  ["utility_electricity_bus:OUT(1)", "other_electricity:IN(0)", "electricity"],
  ["utility_electricity_source:OUT(0)", "utility_electricity_bus:IN(0)", "electricity"],
  ]
############################################################
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = {type = "fixed", value = 0, time_unit="hours"}
duration = 8760 # ...
max_occurrences = 1 # ...
network = "nw"
[scenarios.s1]
time_unit = "hours"
occurrence_distribution = {type = "fixed", value = 87600, time_unit="hours"}
duration = 500 # ...
max_occurrences = -1 # ...
network = "nw"
[scenarios.s2]
time_unit = "hours"
occurrence_distribution = {type = "fixed", value = 87600, time_unit="hours"}
duration = 500 # ...
max_occurrences = -1 # ...
network = "nw"
