
[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "years"
max_time = 100 # ...
############################################################
[loads.mc_electricity_blue_sky]
csv_file = "mc_blue_sky_electricity.csv"
[loads.other_electricity_blue_sky]
csv_file = "other_blue_sky_electricity.csv"
[loads.mc_heating_blue_sky]
csv_file = "mc_blue_sky_heating.csv"
############################################################
[components.mc_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "mc_electricity_blue_sky"

[components.mc_heating]
type = "load"
inflow = "heating"
loads_by_scenario.blue_sky = "mc_heating_blue_sky"

[components.mc_thermal_storage]
type = "store"
outflow = "heating"
inflow = "heating"
capacity_unit = "kWh"
capacity = 100.0
max_inflow = 10.0

[components.other_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "other_electricity_blue_sky"

[components.utility_electricity_bus]
type = "muxer"
stream = "electricity"
num_inflows = 1
num_outflows = 2
dispatch_strategy = "in_order"

[components.utility_electricity_source]
type = "source"
outflow = "electricity"

[components.utility_heating_source]
type = "source"
outflow = "heating"

############################################################
[networks.nw]
connections = [
  ["utility_electricity_bus:OUT(0)", "mc_electricity:IN(0)", "electricity"],
  ["utility_electricity_bus:OUT(1)", "other_electricity:IN(0)", "electricity"],
  ["utility_electricity_source:OUT(0)", "utility_electricity_bus:IN(0)", "electricity"],
  ["mc_thermal_storage:OUT(0)", "mc_heating:IN(0)", "heating"],
  ["utility_heating_source:OUT(0)", "mc_thermal_storage:IN(0)", "heating"],
  ]
############################################################
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = {type = "fixed", value = 0, time_unit="hours"}
duration = 8760 # ...
max_occurrences = 1 # ...
network = "nw"
