
[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "years"
max_time = 100 # ...
############################################################
[loads.mc_electricity_blue_sky]
csv_file = "mc_blue_sky_electricity.csv"
[loads.other_electricity_blue_sky]
csv_file = "other_blue_sky_electricity.csv"
[loads.mc_heating_blue_sky]
csv_file = "mc_blue_sky_heating.csv"
############################################################
[components.utility_electricity_source]
type = "source"
outflow = "electricity"
[components.utility_natural_gas_source]
type = "source"
outflow = "natural_gas"
[components.utility_heating_source]
type = "source"
outflow = "heating"
[components.cluster_0_electric_bus]
type = "muxer"
stream = "electricity"
num_inflows = 1
num_outflows = 2 # ...
dispatch_strategy = "in_order"
[components.mc_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "mc_electricity_blue_sky"
[components.other_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "other_electricity_blue_sky"
[components.mc_heating]
type = "load"
inflow = "heating"
loads_by_scenario.blue_sky = "mc_heating_blue_sky"
[components.mc_gas_boiler]
type = "converter"
outflow = "heating"
inflow = "natural_gas"
lossflow = "waste_heat"
constant_efficiency = 0.85 # ...
[components.mc_heating_manifold]
type = "muxer"
stream = "heating"
num_inflows = 2
num_outflows = 1
dispatch_strategy = "in_order"
############################################################
[networks.nw]
connections = [
  ["utility_electricity_source:OUT(0)", "cluster_0_electric_bus:IN(0)", "electricity"],
  ["cluster_0_electric_bus:OUT(0)", "mc_electricity:IN(0)", "electricity"],
  ["cluster_0_electric_bus:OUT(1)", "other_electricity:IN(0)", "electricity"],
  ["utility_natural_gas_source:OUT(0)", "mc_gas_boiler:IN(0)", "natural_gas"],
  ["mc_gas_boiler:OUT(0)", "mc_heating_manifold:IN(0)", "heating"],
  ["utility_heating_source:OUT(0)", "mc_heating_manifold:IN(1)", "heating"],
  ["mc_heating_manifold:OUT(0)", "mc_heating:IN(0)", "heating"],
  ]
############################################################
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = {type = "fixed", value = 0, time_unit="hours"}
duration = 8760 # ...
max_occurrences = 1 # ...
network = "nw"
