

############################################################
# General Simulation Information
[simulation_info]
rate_unit = "kW"
quantity_unit = "kJ"
time_unit = "years"
max_time = 100 # ...
############################################################
# Load Profiles
[loads.mc_electricity_blue_sky]
csv_file = "mc_blue_sky_electricity.csv"
[loads.other_electricity_blue_sky]
csv_file = "other_blue_sky_electricity.csv"
[loads.mc_heating_blue_sky]
csv_file = "mc_blue_sky_heating.csv"
############################################################
# Components
[components.utility_electricity_source]
type = "source"
outflow = "electricity"
[components.utility_heating_source]
type = "source"
outflow = "heating"
[components.mc_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "mc_electricity_blue_sky"
[components.other_electricity]
type = "load"
inflow = "electricity"
loads_by_scenario.blue_sky = "other_electricity_blue_sky"
[components.mc_heating]
type = "load"
inflow = "heating"
loads_by_scenario.blue_sky = "mc_heating_blue_sky"
[components.mc_heating_store]
type = "store"
inflow = "heating"
outflow = "heating"
capacity_unit = "kWh"
capacity = 100.0 # ...
max_inflow = 10.0 # ...
[components.utility_electricity_bus]
type = "muxer"
stream = "electricity"
num_inflows = 1 # ...
num_outflows = 2 # ...
dispatch_strategy = "in_order"
############################################################
# Fragility Modes
############################################################
# Fragility Curves
############################################################
# Distributions
[dist.always]
type = "fixed"
value = 0.0 # ...
time_unit = "hours"
############################################################
# Failure Modes
############################################################
# Networks
[networks.nw]
connections = [
  ["mc_heating_store:OUT(0)", "mc_heating:IN(0)", "heating"],
  ["utility_electricity_bus:OUT(0)", "mc_electricity:IN(0)", "electricity"],
  ["utility_electricity_bus:OUT(1)", "other_electricity:IN(0)", "electricity"],
  ["utility_electricity_source:OUT(0)", "utility_electricity_bus:IN(0)", "electricity"],
  ["utility_heating_source:OUT(0)", "mc_heating_store:IN(0)", "heating"],
  ]
############################################################
# Scenarios
[scenarios.blue_sky]
time_unit = "hours"
occurrence_distribution = "always"
duration = 8760 # ...
max_occurrences = 1 # ...
calculate_reliability = false
network = "nw"
