name: Build and Test

on: push

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            config: Release
          - os: windows-latest
            config: Release
          - os: macos-latest
            config: Release
          - os: ubuntu-latest
            config: Debug
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.config }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set Project Name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: Configure CMake (non-Ubuntu)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE="${{ matrix.config }}" -DERIN_TESTING="ON"
        if: ${{ matrix.os != 'ubuntu-latest' }}
      - name: Install LLVM and Clang
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "14"
      - name: Configure CMake (Ubuntu)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE="${{ matrix.config }}" -DERIN_TESTING="ON"
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          CC: clang-14
          CXX: clang++-14
      - name: Build
        run: cmake --build build --config ${{ matrix.config }}
      - name: Test
        run: ctest -C ${{ matrix.config }} --output-on-failure
        working-directory: build
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Run Regression Testing
        run: python regress.py
        working-directory: docs/examples
