name: Build and Test

on: push

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            config: Release
          - os: windows-latest
            config: Release
          - os: macos-latest
            config: Release
          - os: ubuntu-latest
            config: Debug
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.config }} coverage=${{ matrix.coverage }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Project Name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE="${{ matrix.config }}" -DERIN_TESTING="ON"
      - name: Build
        run: cmake --build build --config ${{ matrix.config }}
      - name: Test
        run: ctest -C ${{ matrix.config }} --output-on-failure
        working-directory: build
